org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -XX:ReservedCodeCacheSize=1024m -XX:+HeapDumpOnOutOfMemoryError -XX:TieredStopAtLevel=1 -XX:CompileCommand=exclude,com/android/tools/r8/**/* -XX:+UseParallelGC
android.useAndroidX=true
org.gradle.java.home=C:/Program Files/Microsoft/jdk-17.0.0.35-hotspot
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C:/Program Files/Microsoft/jdk-17.0.0.35-hotspot
org.gradle.workers.max=4